MENU_DELAY = 1.6
DAY_DELAY  = 9

STAMP_OPEN_TIME  = 0.5
STAMP_CLOSE_TIME = 0.3

END_DELAY = 5.7
INSPECT_ALPHACHANGE_TIME = 0.5
INSPECT_TIME = 1.5
INSPECT_INTERROGATE_TIME = 2

SHUTTER_OPEN_TIME = 1

CONFISCATE_SLIP_APPEAR_TIME = 0.5
PASSPORT_DRAWER_OPEN_TIME = 1
PASSPORT_DRAWER_CLOSE_TIME = 0.5

GUN_BULLETS_APPEAR_TIME = 1 